Import('baseEnv pkg')
Import('SetupFreeType SetupCppUnit')

try:
    sources = Split('main.cpp FTFontTest.cpp')

    # Clone the environment
    env = baseEnv.Copy()
    env.Append(CPPPATH = ['#src'],
               LIBPATH = ['#src'],
               LIBS = ['gltext'])
    SetupFreeType(env)
    SetupCppUnit(env)

    prog = pkg.createProgram('runtests', env)
    prog.addSources(sources)
except Exception, e:
    print "No cppunit found, not building tests"
    pass
