Import('baseEnv pkg')
Import('SetupFreeType SetupCppUnit')

sources = Split("""
   main.cpp
   FTFontTest.cpp
""")

# Clone the environment
env = baseEnv.Copy()
env['CPPPATH'].extend(['#src'])
env['LIBPATH'].extend(['#src'])
env['LIBS'].extend(['gltext'])
SetupFreeType(env)
SetupCppUnit(env)

prog = pkg.createProgram('runtests', env)
prog.addSources(sources)
