import os
pj = os.path.join

Import('*')

headers = Split("""
   gltext.h
""")

extra = Split("""
   AbstractRenderer.h
   BitmapRenderer.h
   FTFont.h
   FTGlyph.h
   GLGlyph.h
   GLPixelGlyph.h
   GLTextureGlyph.h
   GlyphCache.h
   OpenGL.h
   PixmapRenderer.h
   TextureRenderer.h
""")

sources = Split("""
   gltext.cpp
   AbstractRenderer.cpp
   BitmapRenderer.cpp
   FTFont.cpp
   FTGlyph.cpp
   GLPixelGlyph.cpp
   GLTextureGlyph.cpp
   PixmapRenderer.cpp
   TextureRenderer.cpp
""")

env = baseEnv.Copy(tools=[SetupFreeType, SetupOpenGL])

lib = pkg.createSharedLibrary('gltext', env)
lib.addSources(sources)
lib.addHeaders(headers)

lib = pkg.createStaticLibrary('gltext', env)
lib.addSources(sources)
lib.addHeaders(headers)

def addSrc(n): return os.path.join('src', n)
pkg.addExtraDist(map(addSrc, extra))
