import os
from os import path

Import('baseEnv PREFIX OPENGL_LIBS')

sources = Split("""
   gltext.cpp
   AbstractRenderer.cpp
   BitmapRenderer.cpp
   FTFont.cpp
   FTGlyph.cpp
   FTLibrary.cpp
   GLPixelGlyph.cpp
   PixmapRenderer.cpp
""")

FT2_LIBS = ['freetype']

env = baseEnv.Copy(LIBS=FT2_LIBS + OPENGL_LIBS)

libraries = []
libraries.append(env.Library(target = 'gltext', source = sources))

# Installation
env.Install(path.join(PREFIX, 'include', 'gltext'), 'gltext.h')
env.Install(path.join(PREFIX, 'lib'), libraries)
