import os
pj = os.path.join

Import('*')

sources = Split("""
   gltext.cpp
   AbstractRenderer.cpp
   BitmapRenderer.cpp
   FTFont.cpp
   FTGlyph.cpp
   GLPixelGlyph.cpp
   GLTextureGlyph.cpp
   PixmapRenderer.cpp
   TextureRenderer.cpp
""")

env = baseEnv.Copy(tools=[SetupFreeType, SetupOpenGL])


lib = pkg.createSharedLibrary('gltext', env)
lib.addSources(sources)
lib.addHeaders(['gltext.h'])

lib = pkg.createStaticLibrary('gltext', env)
lib.addSources(sources)
lib.addHeaders(['gltext.h'])
