Import('baseEnv')
Import('SetupFreeType SetupGLUT SetupOpenGL')

# Clone the environment
env = baseEnv.Copy()
env['CPPPATH'].extend(['#src'])
env['LIBPATH'].extend(['#src'])
env['LIBS'].extend(['gltext'])
SetupFreeType(env)
SetupGLUT(env)
SetupOpenGL(env)


env.Program(target = 'sizes', source = 'main.cpp')
