Import('baseEnv pkg')
Import('SetupFreeType SetupGLUT SetupOpenGL')

# Clone the environment
env = baseEnv.Copy()
env.Append(LIBPATH = ['#src'], LIBS = ['gltext'])
SetupFreeType(env)
SetupGLUT(env)
SetupOpenGL(env)

prog = pkg.createProgram('simple', env)
prog.addIncludes(['#src'])
prog.addSources(['simple.cpp'])
