<?php
// $Id: docs.php,v 1.1 2002-06-07 04:55:49 nonchocoboy Exp $
include 'common.inc';
layoutHeader('documentation', 'documentation');
?>

<h1>Documentation</h1>

<h2>GLText API</h2>
<p>
GLText API documentation is automatically generated by <a
href="http://www.doxygen.org">doxygen</a>. The API documentation is available
in the following formats: <br>
<strong>&middot;</strong> Browse <a href="doc/api/">online</a>.<br>
<strong>&middot;</strong> Download as <a href="doc/gltext-api.html.tgz">HTML</a>.<br>
<strong>&middot;</strong> Download as <a href="doc/gltext-api.latex.tgz">LaTeX</a>.<br>
<strong>&middot;</strong> Download as <a href="doc/gltext-api.man.tgz">Man pages</a>.<br>

<h2>Team Docs</h2>
<strong>&middot;</strong> <a href="doc/codingstyle.php">Coding Style Guidelines</a>.<br>

<?php
layoutFooter();
?>
