<?php
// $Id: docs.php,v 1.3 2002-12-24 01:12:59 nonchocoboy Exp $
include 'common.inc';
layoutHeader('documentation', 'documentation');
?>

<h1>Documentation</h1>

<h2>GLText API</h2>
<p>
GLText API documentation is automatically generated by <a
href="http://www.doxygen.org">doxygen</a>. The API documentation is available
in the following formats: <br>
<strong>&middot;</strong> Browse <a href="doc/api/">online</a>.<br>
<strong>&middot;</strong> Download as <a href="doc/gltext-0.2.0-api.html.tar.gz">HTML</a>.<br>
<strong>&middot;</strong> Download as <a href="doc/gltext-0.2.0-api.man.tar.gz">Man pages</a>.<br>

<?php
layoutFooter();
?>
